#SpringBoot启动端口和项目路径
server:
  port: 80
  context-path: /

#SpringMVC中JSP视图配置
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
#datasource
#spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?useUnicode=true&characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.project.business.**.entity

#pagehelper分页插件配置（可以不配）
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
##  supportMethodsArguments: true
#  params: count=countSql

#日志配置 Spring Boot默认会用Logback来记录日志，并用INFO级别输出到控制台
logging:
  #如果是默认文件名logback-spring.xml，则不需要配置
  #config: classpath:logback-spring.xml
  #使用mybatis的时候，sql语句是debug下才会打印，而这里我们只配置了info，所以想要查看sql语句的话
  #单独给dao下目录配置debug模式，代码如下，这样配置sql语句会打印，其他还是正常info级别，推荐用logger标签
  level:
    com:
      project:
        business: debug